export const Urls = {
    concat: (arr) => arr.join(),
    create: "/create",
    test: "/test",
    grade: "/grade",
    short: "/short",
    trans: "/trans",
    prompt: "/prompt",
    wild: "/*",
    process: (url)=> url+Urls.wild,
    myPage: "/myPage",
    testApp: "/testApp",
    testResult: "/testResult",
    qualification: "/qualification",
    transactions: "/transactions",
    profile: "/profile",
    alert: "/alert",
    ask: "/ask",
    logout: "/logout",
}
